nelmio_api_doc:
  areas:
    default:
      path_patterns:
        - ^/api   # Define the path patterns for your API endpoints
      documentation:
        info:
          title: My API
          version: 1.0.0
        securityDefinitions:
        # Define your security definitions if needed
        security:
        # Specify the security requirements for your endpoints