#!/bin/bash
cd /var/www/html

if [ -f composer.json ]; then \
	composer install --prefer-dist --no-autoloader --no-scripts --no-progress; \
	composer clear-cache; \
fi

mkdir -p var/cache var/log; \
   chmod -R 777 var/log
   chmod -R 777 var/cache
   if [ -f composer.json ]; then \
	   composer dump-autoload --classmap-authoritative --no-dev; \
     composer run-script --no-dev post-install-cmd; \
    chmod +x bin/console; sync; \
  fi

cp docker/php/apache/phpinfo.php public/
cp docker/php/apache/.htaccess public/